# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
target 'timvel' do

  pod 'React', path: '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  
  pod 'aliyun-oss-react-native', :path => '../node_modules/aliyun-oss-react-native'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
